In [6]:
import pandas as pd
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.pipeline import Pipeline

In [2]:
male = ['Tom Holland', 'Robert Downey Jr', 'Jason Momoa', 'Hugh Jackman', 'Henry Cavil', 'Dwayne Johnson',
        'Chris Pratt', 'Chris Hemsworth', 'Andy Samberg']

In [3]:
path = 'dataset/training_celeb20x20.csv'
df = pd.read_csv(path, header=0)
df.head(5)

celeb      r1c1      r1c2      r1c3      r1c4      r1c5  \
0  Alexandra Daddario  0.117725  0.098078  0.150353  0.161020  0.137333   
1  Alexandra Daddario  0.799255  0.795843  0.137216  0.367725  0.517490   
2  Alexandra Daddario  0.917922  0.915451  0.921216  0.591647  0.251098   
3  Alexandra Daddario  0.187647  0.191569  0.161412  0.014824  0.073647   
4  Alexandra Daddario  0.948392  0.878667  0.850627  0.777569  0.640000   

       r1c6      r1c7      r1c8      r1c9  ...    r20c11    r20c12    r20c13  \
0  0.137882  0.089137  0.202824  0.154471  ...  0.309020  0.372824  0.153686   
1  0.325882  0.093843  0.140667  0.043569  ...  0.564157  0.537804  0.589569   
2  0.303216  0.259843  0.236078  0.175529  ...  0.554627  0.628392  0.537020   
3  0.057961  0.022667  0.156000  0.203922  ...  0.669725  0.732471  0.750745   
4  0.646392  0.724549  0.674745  0.572510  ...  0.356078  0.329882  0.281608   

     r20c14    r20c15    r20c16    r20c17    r20c18    r20c19    r20c20  
0  0.212118  0.169529  0.173294  0.609569  0.359922  0.427176  0.439961  
1  0.541412  0.224000  0.063608  0.952706  0.863765  0.809137  0.788118  
2  0.369490  0.266431  0.231882  0.204314  0.278667  0.283686  0.380941  
3  0.759922  0.812000  0.745373  0.698039  0.601882  0.549765  0.457569  
4  0.350000  0.243529  0.047922  0.090275  0.128863  0.072314  0.126941  

[5 rows x 401 columns]

In [5]:
x = df.iloc[:, 1:]
y = df.iloc[:, 0]
y_gender = [1 if i in male else 0 for i in y]
y_gender

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [7]:
pipeline = Pipeline([
    ('min_max_scaler', MinMaxScaler()),
    ('std_scaler', StandardScaler())
])

X_train, X_test, y_train, y_test = train_test_split(x, y_gender, test_size=0.3, random_state=42)

In [8]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train == False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

In [9]:
from sklearn.svm import LinearSVC

model = LinearSVC(loss='hinge', dual=True)
model.fit(X_train, y_train)

print_score(model, X_train, y_train, X_test, y_test, train=True)
print_score(model, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 88.09%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy    macro avg  weighted avg
precision     0.882123     0.879392  0.880891     0.880758      0.880863
recall        0.898966     0.859796  0.880891     0.879381      0.880891
f1-score      0.890465     0.869484  0.880891     0.879974      0.880783
support    1257.000000  1077.000000  0.880891  2334.000000   2334.000000
_______________________________________________
Confusion Matrix: 
 [[1130  127]
 [ 151  926]]

Test Result:
Accuracy Score: 78.72%
_______________________________________________
CLASSIFICATION REPORT:
                    0           1  accuracy    macro avg  weighted avg
precision    0.785311    0.789362  0.787213     0.787336      0.787273
recall       0.808140    0.764948  0.787213     0.786544      0.787213
f1-score     0.796562    0.776963  0.787213     0.786762      0.787066
support    516.000000  485.000000  0.787

/Users/benminh1201/miniconda3/envs/massey/lib/python3.11/site-packages/sklearn/svm/_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [10]:
from sklearn.svm import SVC

# The hyperparameter coef0 controls how much the model is influenced by high degree ploynomials 
model = SVC(kernel='poly', degree=2, gamma='auto', coef0=1, C=5)
model.fit(X_train, y_train)

print_score(model, X_train, y_train, X_test, y_test, train=True)
print_score(model, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 86.38%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy    macro avg  weighted avg
precision     0.868814     0.857681  0.863753     0.863248      0.863677
recall        0.879873     0.844940  0.863753     0.862406      0.863753
f1-score      0.874308     0.851263  0.863753     0.862786      0.863674
support    1257.000000  1077.000000  0.863753  2334.000000   2334.000000
_______________________________________________
Confusion Matrix: 
 [[1106  151]
 [ 167  910]]

Test Result:
Accuracy Score: 81.22%
_______________________________________________
CLASSIFICATION REPORT:
                    0           1  accuracy    macro avg  weighted avg
precision    0.809434    0.815287  0.812188     0.812360      0.812270
recall       0.831395    0.791753  0.812188     0.811574      0.812188
f1-score     0.820268    0.803347  0.812188     0.811807      0.812069
support    516.000000  485.000000  0.812

In [11]:
model = SVC(kernel='rbf', gamma=0.5, C=0.1)
model.fit(X_train, y_train)

print_score(model, X_train, y_train, X_test, y_test, train=True)
print_score(model, X_train, y_train, X_test, y_test, train=False)

/Users/benminh1201/miniconda3/envs/massey/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/benminh1201/miniconda3/envs/massey/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/benminh1201/miniconda3/envs/massey/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier

Train Result:
Accuracy Score: 53.86%
_______________________________________________
CLASSIFICATION REPORT:
                     0       1  accuracy    macro avg  weighted avg
precision     0.538560     0.0   0.53856     0.269280      0.290047
recall        1.000000     0.0   0.53856     0.500000      0.538560
f1-score      0.700084     0.0   0.53856     0.350042      0.377037
support    1257.000000  1077.0   0.53856  2334.000000   2334.000000
_______________________________________________
Confusion Matrix: 
 [[1257    0]
 [1077    0]]

Test Result:
Accuracy Score: 51.55%
_______________________________________________
CLASSIFICATION REPORT:
                    0      1  accuracy    macro avg  weighted avg
precision    0.515485    0.0  0.515485     0.257742      0.265724
recall       1.000000    0.0  0.515485     0.500000      0.515485
f1-score     0.680290    0.0  0.515485     0.340145      0.350679
support    516.000000  485.0  0.515485  1001.000000   1001.000000
___________________

/Users/benminh1201/miniconda3/envs/massey/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/benminh1201/miniconda3/envs/massey/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/benminh1201/miniconda3/envs/massey/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier

In [12]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
scaler = StandardScaler()

X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
pca.n_components_

193

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.01, 0.1, 0.5, 1, 10, 100],
              'gamma': [1, 0.75, 0.5, 0.25, 0.1, 0.01, 0.001],
              'kernel': ['rbf', 'poly', 'linear']}

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=1, cv=5)
grid.fit(X_train, y_train)
best_params = grid.best_params_
print(f"Best params: {best_params}")

svm_clf = SVC(**best_params)
svm_clf.fit(X_train, y_train)

print_score(svm_clf, X_train, y_train, X_test, y_test, train=True)
print_score(svm_clf, X_train, y_train, X_test, y_test, train=False)

Fitting 5 folds for each of 126 candidates, totalling 630 fits
